language: python
matrix:
  include:
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7
      cache: pip
      before_install:
        - python --version
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov-report term --cov=planetoids test/test.py
      after_success:
        - codecov
    - name: "Python 3.7 on OSX"
      os: osx
      osx_image: xcode10.2
      language: shell
      python: 3.7
      before_install:
        - python3 --version
        - pip3 install -U pip
      install:
        - python3 -m pip install -r requirements.txt
      script:
        - python3 -m pytest --cov-report term --cov=planetoids test/test.py
      after_success:
        - python3 -m codecov
    # - name: "Python 3.7 on Windows"
    #   os: windows
    #   language: shell
    #   before_install:
    #     - choco install python --version 3.7
    #     - python --version
    #     - python -m pip install --upgrade pip
    #     - pip3 install --upgrade pytest
    #     - pip3 install codecov
    #     - pip3 install https://download.lfd.uci.edu/pythonlibs/g5apjq5m/Shapely-1.6.4.post2-cp37-cp37m-win_amd64.whl
    #     - pip3 install https://download.lfd.uci.edu/pythonlibs/g5apjq5m/opencv_python-3.4.7-cp37-cp37m-win_amd64.whl
    #   env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   install:
    #     - python -m pip install -r requirements.txt
    #   script:
    #     - python -m pytest --cov-report term --cov=planetoids test/test.py
    #   after_success:
    #     - python -m codecov
