language: python
matrix:
  include:
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7
      cache: pip
      before_install:
        - python --version
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov-report term --cov=planetoids test/test.py
      after_success:
        - codecov
    - name: "Python 3.7 on OSX"
      os: osx
      osx_image: xcode10.2
      language: shell
      python: 3.7
      before_install:
        - python3 --version
        - pip3 install -U pip
      install:
        - python3 -m pip install -r requirements.txt
      script:
        - python3 -m pytest --cov-report term --cov=planetoids test/test.py
      after_success:
        - python3 -m codecov
